# Generated by Django 5.1.8 on 2025-04-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='field_1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Поле_1'),
        ),
        migrations.AlterField(
            model_name='client',
            name='field_2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Поле_2'),
        ),
        migrations.AlterField(
            model_name='client',
            name='field_3',
            field=models.CharField(blank=True, max_length=100, verbose_name='Поле_3'),
        ),
        migrations.AlterField(
            model_name='moderator',
            name='field_1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Поле_1'),
        ),
        migrations.AlterField(
            model_name='moderator',
            name='field_2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Поле_2'),
        ),
        migrations.AlterField(
            model_name='moderator',
            name='field_3',
            field=models.CharField(blank=True, max_length=100, verbose_name='Поле_3'),
        ),
    ]
